import type { ExportFunction, DraftConfig } from './types';

export const DEFAULT_EXPORT_FUNCTIONS: ExportFunction[] = [
  {
    enabled: true,
    function_key: 'raw_account_daily',
    display_name: 'Account Daily',
    destination_tab: 'raw_account_daily',
    date_grain: 'DAY',
    max_rows: 365,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'customer',
    compatibility_notes: 'Use customer resource only. Do not mix campaign segments.',
  },
  {
    enabled: true,
    function_key: 'raw_campaign_daily',
    display_name: 'Campaign Daily',
    destination_tab: 'raw_campaign_daily',
    date_grain: 'DAY',
    max_rows: 5000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'campaign',
    compatibility_notes: 'Safe to select campaign.* fields from campaign resource.',
  },
  {
    enabled: true,
    function_key: 'raw_ad_group_daily',
    display_name: 'Ad Group Daily',
    destination_tab: 'raw_ad_group_daily',
    date_grain: 'DAY',
    max_rows: 10000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'ad_group',
    compatibility_notes: 'Select from ad_group resource. Avoid mixing with campaign_search_term_view.',
  },
  {
    enabled: true,
    function_key: 'raw_keyword_daily',
    display_name: 'Keyword Daily',
    destination_tab: 'raw_keyword_daily',
    date_grain: 'DAY',
    max_rows: 20000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'ad_group_criterion',
    compatibility_notes: 'Filter WHERE ad_group_criterion.type = KEYWORD.',
  },
  {
    enabled: true,
    function_key: 'raw_search_terms_daily',
    display_name: 'Search Terms Daily',
    destination_tab: 'raw_search_terms_daily',
    date_grain: 'DAY',
    max_rows: 10000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: 'May be large',
    gaql_resource_rule: 'search_term_view',
    compatibility_notes: 'Do not use campaign_search_term_view.status — unrecognized field. Use search_term_view only.',
  },
  {
    enabled: true,
    function_key: 'raw_pmax_asset_group_daily',
    display_name: 'PMax Asset Group Daily',
    destination_tab: 'raw_pmax_asset_group_daily',
    date_grain: 'DAY',
    max_rows: 1000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: 'Requires ENABLE_PMAX_EXPORTS = true',
    gaql_resource_rule: 'asset_group',
    compatibility_notes: 'Do NOT select segments.asset_interaction_target.asset from asset_group — incompatible.',
  },
  {
    enabled: true,
    function_key: 'raw_pmax_terms_daily',
    display_name: 'PMax Terms Daily',
    destination_tab: 'raw_pmax_terms_daily',
    date_grain: 'DAY',
    max_rows: 5000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: 'Requires ENABLE_PMAX_EXPORTS = true',
    gaql_resource_rule: 'shopping_performance_view',
    compatibility_notes: 'Use shopping_performance_view for PMax term-level data.',
  },
  {
    enabled: true,
    function_key: 'raw_geo_daily',
    display_name: 'Geo Daily',
    destination_tab: 'raw_geo_daily',
    date_grain: 'DAY',
    max_rows: 5000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'geographic_view',
    compatibility_notes: 'Do NOT select segments.geo_target_country from geographic_view — incompatible segment.',
  },
  {
    enabled: true,
    function_key: 'raw_device_daily',
    display_name: 'Device Daily',
    destination_tab: 'raw_device_daily',
    date_grain: 'DAY',
    max_rows: 500,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'campaign',
    compatibility_notes: 'Segment by segments.device from campaign resource.',
  },
  {
    enabled: true,
    function_key: 'raw_conversion_action_daily',
    display_name: 'Conversion Action Daily',
    destination_tab: 'raw_conversion_action_daily',
    date_grain: 'DAY',
    max_rows: 2000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'conversion_action',
    compatibility_notes: 'Select from conversion_action resource.',
  },
  {
    enabled: true,
    function_key: 'raw_budget_daily',
    display_name: 'Budget Daily',
    destination_tab: 'raw_budget_daily',
    date_grain: 'DAY',
    max_rows: 500,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'campaign_budget',
    compatibility_notes: 'Select from campaign_budget resource.',
  },
  {
    enabled: true,
    function_key: 'raw_change_history_daily',
    display_name: 'Change History Daily',
    destination_tab: 'raw_change_history_daily',
    date_grain: 'DAY',
    max_rows: 2000,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: '',
    gaql_resource_rule: 'change_event',
    compatibility_notes: 'Select from change_event resource. Do not select campaign.* fields from this resource.',
  },
  {
    enabled: true,
    function_key: 'raw_script_health',
    display_name: 'Script Health',
    destination_tab: '_script_health',
    date_grain: 'RUN',
    max_rows: 1000,
    lookback_days_override: null,
    write_mode: 'append',
    status: 'active',
    notes: 'Written by script on each run',
    gaql_resource_rule: 'N/A - internal',
    compatibility_notes: 'No GAQL query. Written directly by script runtime.',
  },
  {
    enabled: true,
    function_key: 'raw_sync_runs',
    display_name: 'Sync Runs',
    destination_tab: '_sync_runs',
    date_grain: 'RUN',
    max_rows: 1000,
    lookback_days_override: null,
    write_mode: 'append',
    status: 'active',
    notes: 'Audit trail of each sync run',
    gaql_resource_rule: 'N/A - internal',
    compatibility_notes: 'No GAQL query. Written directly by script runtime.',
  },
  {
    enabled: true,
    function_key: 'raw_errors',
    display_name: 'Errors Log',
    destination_tab: '_error_log',
    date_grain: 'RUN',
    max_rows: 500,
    lookback_days_override: null,
    write_mode: 'append',
    status: 'active',
    notes: 'Captures script errors',
    gaql_resource_rule: 'N/A - internal',
    compatibility_notes: 'No GAQL query. Written by error handler.',
  },
  {
    enabled: true,
    function_key: 'raw_dashboard_summary',
    display_name: 'Dashboard Summary',
    destination_tab: 'dashboard_summary_daily',
    date_grain: 'DAY',
    max_rows: 365,
    lookback_days_override: null,
    write_mode: 'overwrite',
    status: 'active',
    notes: 'Aggregated summary for dashboard',
    gaql_resource_rule: 'customer',
    compatibility_notes: 'Derived from customer resource aggregate query.',
  },
];

export const SHEET_TABS = {
  core: [
    { tab: 'README', description: 'Project readme, deployment instructions, checklist' },
    { tab: '_settings_global', description: 'Global settings key/value store' },
    { tab: '_settings_account', description: 'Account-specific settings' },
    { tab: '_settings_exporter', description: 'Google Ads script exporter settings' },
    { tab: '_settings_bridge', description: 'Apps Script bridge settings' },
    { tab: '_settings_dashboard', description: 'Dashboard display and alert settings' },
    { tab: '_export_jobs', description: 'Export job configuration and last-run status' },
    { tab: '_tab_manifest', description: 'List of all tabs in this workbook' },
    { tab: '_field_manifest', description: 'Field definitions per export job' },
    { tab: '_gaql_compatibility_matrix', description: 'GAQL resource/segment safety rules' },
    { tab: '_qa_checklist', description: 'QA and deployment checklist' },
    { tab: '_script_health', description: 'Script health monitoring log' },
    { tab: '_sync_runs', description: 'Audit trail of sync runs' },
    { tab: '_error_log', description: 'Script error log' },
  ],
  rawData: [
    { tab: 'raw_account_daily', description: 'Account-level daily metrics' },
    { tab: 'raw_campaign_daily', description: 'Campaign-level daily metrics' },
    { tab: 'raw_ad_group_daily', description: 'Ad group-level daily metrics' },
    { tab: 'raw_keyword_daily', description: 'Keyword-level daily metrics' },
    { tab: 'raw_search_terms_daily', description: 'Search terms daily report' },
    { tab: 'raw_pmax_asset_group_daily', description: 'PMax asset group daily' },
    { tab: 'raw_pmax_terms_daily', description: 'PMax terms daily' },
    { tab: 'raw_geo_daily', description: 'Geographic performance daily' },
    { tab: 'raw_device_daily', description: 'Device performance daily' },
    { tab: 'raw_conversion_action_daily', description: 'Conversion action daily' },
    { tab: 'raw_budget_daily', description: 'Budget utilization daily' },
    { tab: 'raw_change_history_daily', description: 'Change history daily' },
  ],
  dashboard: [
    { tab: 'dashboard_summary_daily', description: 'Dashboard summary aggregated daily' },
    { tab: 'dashboard_campaign_daily', description: 'Dashboard campaign view daily' },
    { tab: 'dashboard_pmax_daily', description: 'Dashboard PMax view daily' },
    { tab: 'dashboard_geo_daily', description: 'Dashboard geo view daily' },
    { tab: 'dashboard_terms_daily', description: 'Dashboard search terms view daily' },
    { tab: 'dashboard_conversion_daily', description: 'Dashboard conversions view daily' },
  ],
  mapping: [
    { tab: 'map_accounts', description: 'Account mapping reference' },
    { tab: 'map_campaigns', description: 'Campaign mapping reference' },
    { tab: 'map_ad_groups', description: 'Ad group mapping reference' },
    { tab: 'map_conversion_actions', description: 'Conversion action mapping' },
    { tab: 'map_geo_targets', description: 'Geo target mapping' },
    { tab: 'map_channels', description: 'Channel type mapping' },
  ],
};

export const TIMEZONES = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Anchorage',
  'Pacific/Honolulu',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Asia/Tokyo',
  'Asia/Singapore',
  'Australia/Sydney',
  'UTC',
];

export const CURRENCIES = [
  'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'SGD', 'CHF', 'HKD', 'NZD',
];

export function createDefaultDraft(partial?: Partial<DraftConfig>): DraftConfig {
  return {
    id: crypto.randomUUID(),
    name: 'New Draft',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    templateType: 'google_ads_account',
    accountNickname: '',
    customerId: '',
    timezone: 'America/New_York',
    currency: 'USD',
    ownerEmail: '',
    environment: 'test',
    lookbackDays: 30,
    exportScheduleNote: '',
    dashboardProjectName: '',
    accountId: '',
    accountName: '',
    sheetVersion: '1.0.0',
    scriptVersion: '1.0.0',
    adsApiVersion: 'v18',
    maxRowsDefault: 5000,
    maxRowsPmax: 1000,
    maxRowsTerms: 10000,
    dateRangeMode: 'LAST_30_DAYS',
    writeMode: 'overwrite',
    includeZeroImpressions: false,
    includeRemovedEntities: false,
    enableDebugLogs: false,
    exportFunctions: DEFAULT_EXPORT_FUNCTIONS.map(f => ({ ...f })),
    isMccChildAccount: false,
    mccParentCustomerId: '',
    bridgeEnabled: false,
    bridgeTokenPlaceholder: 'REPLACE_WITH_YOUR_BRIDGE_TOKEN',
    bridgeEndpointUrl: 'https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec',
    dashboardImportMode: 'pull',
    allowGet: true,
    allowPost: true,
    enableHealthEndpoint: true,
    enableCsvExport: true,
    enableJsonExport: true,
    enableCache: true,
    cacheSeconds: 300,
    logBridgeRequests: false,
    dashboardEnabled: false,
    dashboardAccountName: '',
    dashboardRefreshIntervalMinutes: 60,
    showLastSyncCard: true,
    showScriptHealthCard: true,
    showCampaignTable: true,
    showPmaxTable: true,
    showSearchTermsTable: true,
    showGeoTable: true,
    showConversionTable: true,
    alertIfSyncOlderThanHours: 26,
    alertIfScriptErrorCountGt: 0,
    alertIfCostSpikePercentGt: 50,
    alertIfConversionDropPercentGt: 30,
    ...partial,
  };
}

export function applyTemplateDefaults(
  existing: DraftConfig,
  templateType: import('./types').TemplateType,
): DraftConfig {
  const base = {
    accountNickname: existing.accountNickname,
    customerId: existing.customerId,
    ownerEmail: existing.ownerEmail,
    timezone: existing.timezone,
    currency: existing.currency,
  };

  switch (templateType) {
    case 'google_ads_account':
      return createDefaultDraft({
        ...base,
        templateType: 'google_ads_account',
        environment: 'test',
        enableDebugLogs: false,
        exportFunctions: DEFAULT_EXPORT_FUNCTIONS.map(f => ({ ...f, enabled: true })),
        isMccChildAccount: false,
        mccParentCustomerId: '',
      });

    case 'test_account':
      return createDefaultDraft({
        ...base,
        templateType: 'test_account',
        environment: 'test',
        enableDebugLogs: true,
        maxRowsDefault: 1000,
        maxRowsPmax: 500,
        maxRowsTerms: 1000,
        exportFunctions: DEFAULT_EXPORT_FUNCTIONS.map(f => ({ ...f, enabled: true })),
        isMccChildAccount: false,
        mccParentCustomerId: '',
      });

    case 'mcc_child':
      return createDefaultDraft({
        ...base,
        templateType: 'mcc_child',
        environment: 'test',
        enableDebugLogs: false,
        exportFunctions: DEFAULT_EXPORT_FUNCTIONS.map(f => ({ ...f, enabled: true })),
        isMccChildAccount: true,
        mccParentCustomerId: existing.mccParentCustomerId || '',
      });

    case 'empty_developer':
      return createDefaultDraft({
        ...base,
        templateType: 'empty_developer',
        environment: 'test',
        enableDebugLogs: true,
        exportFunctions: DEFAULT_EXPORT_FUNCTIONS.map(f => ({ ...f, enabled: false })),
        isMccChildAccount: false,
        mccParentCustomerId: '',
      });

    default:
      return { ...existing, templateType };
  }
}
